import {
  archiveContactSchema,
  createContactSchema,
  createTaskSchema,
  enrichContactSchema,
  getContactSchema,
  listWorkflowTemplatesSchema,
  queryAnalyticsSchema,
  queryContactsSchema,
  queryContentSchema,
  queryGoalsSchema,
  queryWorkflowsSchema,
  startWorkflowSchema,
  updateContactSchema,
  getPersonaSchema,
  upsertPersonaSchema,
} from "@/lib/agent-tools/schemas";
import {
  logInteractionSchema,
  queryGraphSchema,
  queryNichesSchema,
  queryOrgsSchema,
  queryLaunchesSchema,
  queryOrgIdentitiesSchema,
  upsertEdgeSchema,
  upsertLaunchSchema,
  upsertNicheSchema,
  upsertOrgIdentitySchema,
  upsertVariantSchema,
  semanticSearchSchema,
  createSimulationRunSchema,
  querySimulationsSchema,
  recordSimulationResultsSchema,
  completeSimulationRunSchema,
  calibrateSimulationRunSchema,
} from "@/lib/agent-tools/graph-schemas";
import {
  handleLogInteraction,
  handleQueryGraph,
  handleQueryLaunches,
  handleQueryNiches,
  handleQueryOrgIdentities,
  handleQueryOrgs,
  handleSemanticSearch,
  handleUpsertEdge,
  handleUpsertLaunch,
  handleUpsertNiche,
  handleUpsertOrgIdentity,
  handleUpsertVariant,
  handleCreateSimulationRun,
  handleQuerySimulations,
  handleRecordSimulationResults,
  handleCompleteSimulationRun,
  handleCalibrateSimulationRun,
} from "@/lib/agent-tools/graph-handlers";
import {
  completeSimulationRunParameters,
  zodToParameters,
} from "@/lib/agent-tools/json-schema";
import {
  handleArchiveContact,
  handleCreateContact,
  handleCreateTask,
  handleEnrichContact,
  handleGetContact,
  handleListWorkflowTemplates,
  handleQueryAnalytics,
  handleQueryContacts,
  handleQueryContent,
  handleQueryGoals,
  handleQueryWorkflows,
  handleStartWorkflow,
  handleUpdateContact,
  handleGetPersona,
  handleUpsertPersona,
} from "@/lib/agent-tools/handlers";
import type { AgentToolDefinition } from "@/lib/agent-tools/types";

export const AGENT_TOOL_VERSION = "1";

export const AGENT_TOOLS: Record<string, AgentToolDefinition> = {
  query_contacts: {
    name: "query_contacts",
    description:
      "Search and filter contacts by name, email, company, funnel stage, or platform.",
    category: "contacts",
    schema: queryContactsSchema,
    parameters: zodToParameters(queryContactsSchema),
    execute: handleQueryContacts,
  },
  get_contact: {
    name: "get_contact",
    description: "Get full details for a single contact by ID, including linked identities.",
    category: "contacts",
    schema: getContactSchema,
    parameters: zodToParameters(getContactSchema),
    execute: handleGetContact,
  },
  create_contact: {
    name: "create_contact",
    description: "Create a new contact record. At minimum a name is required.",
    category: "contacts",
    schema: createContactSchema,
    parameters: zodToParameters(createContactSchema),
    execute: handleCreateContact,
  },
  update_contact: {
    name: "update_contact",
    description: "Update fields on an existing contact by ID.",
    category: "contacts",
    schema: updateContactSchema,
    parameters: zodToParameters(updateContactSchema),
    execute: handleUpdateContact,
  },
  enrich_contact: {
    name: "enrich_contact",
    description:
      "Fill missing contact fields without overwriting existing data. Recalculates enrichment score.",
    category: "contacts",
    schema: enrichContactSchema,
    parameters: zodToParameters(enrichContactSchema),
    execute: handleEnrichContact,
  },
  archive_contact: {
    name: "archive_contact",
    description: "Archive a contact with a reason.",
    category: "contacts",
    schema: archiveContactSchema,
    parameters: zodToParameters(archiveContactSchema),
    execute: handleArchiveContact,
  },
  query_analytics: {
    name: "query_analytics",
    description:
      "Get CRM dashboard metrics: total contacts, active workflows, pending tasks, and content count.",
    category: "analytics",
    schema: queryAnalyticsSchema,
    parameters: zodToParameters(queryAnalyticsSchema),
    execute: handleQueryAnalytics,
  },
  query_workflows: {
    name: "query_workflows",
    description:
      "List automation runs. Filter by type (sync, enrich, search, prune, sequence, agent) or status.",
    category: "workflows",
    schema: queryWorkflowsSchema,
    parameters: zodToParameters(queryWorkflowsSchema),
    execute: handleQueryWorkflows,
  },
  list_workflow_templates: {
    name: "list_workflow_templates",
    description: "List available agent/workflow templates that can be started.",
    category: "workflows",
    schema: listWorkflowTemplatesSchema,
    parameters: zodToParameters(listWorkflowTemplatesSchema),
    execute: handleListWorkflowTemplates,
  },
  start_workflow: {
    name: "start_workflow",
    description: "Start an agent workflow from a template ID.",
    category: "workflows",
    schema: startWorkflowSchema,
    parameters: zodToParameters(startWorkflowSchema),
    execute: handleStartWorkflow,
  },
  query_content: {
    name: "query_content",
    description:
      "List content items. Filter by content type (post, thread, article, newsletter, dm, reply) or status.",
    category: "content",
    schema: queryContentSchema,
    parameters: zodToParameters(queryContentSchema),
    execute: handleQueryContent,
  },
  query_goals: {
    name: "query_goals",
    description: "List and filter goals by status or type.",
    category: "goals",
    schema: queryGoalsSchema,
    parameters: zodToParameters(queryGoalsSchema),
    execute: handleQueryGoals,
  },
  create_task: {
    name: "create_task",
    description: "Create a follow-up task, optionally linked to a contact.",
    category: "tasks",
    schema: createTaskSchema,
    parameters: zodToParameters(createTaskSchema),
    execute: handleCreateTask,
  },
  get_persona: {
    name: "get_persona",
    description:
      "Get the active AI persona for a contact (archetype, tone, interests, conversion triggers).",
    category: "contacts",
    schema: getPersonaSchema,
    parameters: zodToParameters(getPersonaSchema),
    execute: handleGetPersona,
  },
  upsert_persona: {
    name: "upsert_persona",
    description:
      "Save a new active persona for a contact; supersedes any previous active persona (versioned history).",
    category: "contacts",
    schema: upsertPersonaSchema,
    parameters: zodToParameters(upsertPersonaSchema),
    execute: handleUpsertPersona,
  },
  query_orgs: {
    name: "query_orgs",
    description: "Search organization nodes in the graph.",
    category: "graph",
    schema: queryOrgsSchema,
    parameters: zodToParameters(queryOrgsSchema),
    execute: handleQueryOrgs,
  },
  query_org_identities: {
    name: "query_org_identities",
    description: "List org platform identities with profile and stat fields.",
    category: "graph",
    schema: queryOrgIdentitiesSchema,
    parameters: zodToParameters(queryOrgIdentitiesSchema),
    execute: handleQueryOrgIdentities,
  },
  upsert_org_identity: {
    name: "upsert_org_identity",
    description:
      "Create or update an org platform identity. Cross-claim conflicts return a reassign error.",
    category: "graph",
    schema: upsertOrgIdentitySchema,
    parameters: zodToParameters(upsertOrgIdentitySchema),
    execute: handleUpsertOrgIdentity,
  },
  query_graph: {
    name: "query_graph",
    description: "Traverse 1-hop graph edges from a node. Private edges excluded unless includeLocalOnly is true.",
    category: "graph",
    schema: queryGraphSchema,
    parameters: zodToParameters(queryGraphSchema),
    execute: handleQueryGraph,
  },
  upsert_edge: {
    name: "upsert_edge",
    description: "Create or update a typed graph edge between two nodes.",
    category: "graph",
    schema: upsertEdgeSchema,
    parameters: zodToParameters(upsertEdgeSchema),
    execute: handleUpsertEdge,
  },
  log_interaction: {
    name: "log_interaction",
    description: "Append an interaction event for a contact (meetings, calls, messages, notes).",
    category: "graph",
    schema: logInteractionSchema,
    parameters: zodToParameters(logInteractionSchema),
    execute: handleLogInteraction,
  },
  query_niches: {
    name: "query_niches",
    description: "List or search niche clusters with member counts. Private niches excluded unless includeLocalOnly is true.",
    category: "graph",
    schema: queryNichesSchema,
    parameters: zodToParameters(queryNichesSchema),
    execute: handleQueryNiches,
  },
  upsert_niche: {
    name: "upsert_niche",
    description: "Create or update a niche cluster. Use upsert_edge with belongs_to_niche for membership.",
    category: "graph",
    schema: upsertNicheSchema,
    parameters: zodToParameters(upsertNicheSchema),
    execute: handleUpsertNiche,
  },
  query_launches: {
    name: "query_launches",
    description:
      "List GTM launches with variant summaries and linked goal IDs. Private launches excluded unless includeLocalOnly is true.",
    category: "graph",
    schema: queryLaunchesSchema,
    parameters: zodToParameters(queryLaunchesSchema),
    execute: handleQueryLaunches,
  },
  upsert_launch: {
    name: "upsert_launch",
    description: "Create or update a GTM launch by explicit id (insert when id omitted).",
    category: "graph",
    schema: upsertLaunchSchema,
    parameters: zodToParameters(upsertLaunchSchema),
    execute: handleUpsertLaunch,
  },
  upsert_variant: {
    name: "upsert_variant",
    description:
      "Create or update a creative variant under a launch. status:'published' routes through publishVariant. predicted_* fields are manual overrides; use create_simulation_run / complete_simulation_run for Wind Tunnel projections.",
    category: "graph",
    schema: upsertVariantSchema,
    parameters: zodToParameters(upsertVariantSchema),
    execute: handleUpsertVariant,
  },
  semantic_search: {
    name: "semantic_search",
    description:
      "Top-k semantic search over embedded graph nodes. Embeds the query via RealtimeX and searches local vectors.",
    category: "graph",
    schema: semanticSearchSchema,
    parameters: zodToParameters(semanticSearchSchema),
    execute: handleSemanticSearch,
  },
  create_simulation_run: {
    name: "create_simulation_run",
    description:
      "Create a Wind Tunnel simulation run for a variant, materialize a grounded agent population, and start the run atomically.",
    category: "graph",
    schema: createSimulationRunSchema,
    parameters: zodToParameters(createSimulationRunSchema),
    execute: handleCreateSimulationRun,
  },
  query_simulations: {
    name: "query_simulations",
    description:
      "List simulation run history and results by variant, launch, or batch. Transcripts are not included.",
    category: "graph",
    schema: querySimulationsSchema,
    parameters: zodToParameters(querySimulationsSchema),
    execute: handleQuerySimulations,
  },
  record_simulation_results: {
    name: "record_simulation_results",
    description:
      "Batch per-agent simulation outcomes for a running simulation run. Idempotent per agentId.",
    category: "graph",
    schema: recordSimulationResultsSchema,
    parameters: zodToParameters(recordSimulationResultsSchema),
    execute: handleRecordSimulationResults,
  },
  complete_simulation_run: {
    name: "complete_simulation_run",
    description:
      "Finish a simulation run and project latest predictions onto the parent variant when completed. status defaults to 'completed', which requires predictedScore (0–100), predictionConfidence (0–1), and predictedMetrics (engagement_metrics keyspace, e.g. { likes: 120 }). failed requires error; cancelled accepts optional error. Neither failed nor cancelled projects scores.",
    category: "graph",
    schema: completeSimulationRunSchema,
    parameters: completeSimulationRunParameters(),
    execute: handleCompleteSimulationRun,
  },
  calibrate_simulation_run: {
    name: "calibrate_simulation_run",
    description:
      "Compute predicted-vs-actual calibration for a completed simulation run on a published variant.",
    category: "graph",
    schema: calibrateSimulationRunSchema,
    parameters: zodToParameters(calibrateSimulationRunSchema),
    execute: handleCalibrateSimulationRun,
  },
};

export function listAgentToolsManifest() {
  return {
    version: AGENT_TOOL_VERSION,
    tools: Object.values(AGENT_TOOLS).map((tool) => ({
      name: tool.name,
      description: tool.description,
      category: tool.category,
      parameters: tool.parameters,
    })),
  };
}
